hugoblox:
  schema: "2.0"
  identity:
    name: Dr Arno Germond
    type: person
    tagline: Deciphering Biology
    description: |-
      Biological systems are complex, but predictable.
      I develop innovative tools for biomedical and food processing.
  theme:
    mode: system
    pack: minimal
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
  identity:
    name: Dr. Arno Germond
    organization: INRAE
    tagline: Cell Biology Researcher
    description: "Dr Arno Germond is a cell biologist aiming to decode information in complex biology systems "
  seo:
    title: Arno GERMOND AI scientist
    location:
      address:
        region: Auvergne
        postal_code: "63000"
        country: FRANCE
        city: Clermont Ferrand
  repository:
    url: https://github.com/ArnoGermond
